name: CI

on: [push, pull_requests]

env:
  DATABASE_URL: "https://fake.com"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Install Dependencies
        run: npm install

      - name: TypeScript
        run: npm run typecheck

      - name: Lint
        run: npm run lint
